# fly.toml app configuration file generated for navidrome-dev on 2025-08-09T16:22:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = 'lhr'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mount]
source = "navidrome_data"
destination = "/data"
initial_size = '1gb'
auto_extend_size_threshold = 80
auto_extend_size_increment = '1gb'
auto_extend_size_limit = '10gb'
